[package]
name = "vectorcraft-pdf"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "VectorCraft PDF export and import"

[lints]
workspace = true

[dependencies]
vectorcraft-geom = { workspace = true }
vectorcraft-doc = { workspace = true }
vectorcraft-effects = { workspace = true }
vectorcraft-color = { workspace = true }
vectorcraft-text = { workspace = true }
kurbo = { workspace = true }
thiserror = { workspace = true }
image = { workspace = true }
krilla = { workspace = true }
hayro-syntax = "0.7.2"
hayro-interpret = { version = "0.7.0", default-features = false, features = ["embed-fonts"] }
log = { workspace = true }
smallvec = "1"
