[package]
name = "drawcraft-geom"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "DrawCraft geom"

[lints]
workspace = true

[dependencies]
kurbo = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
proptest = { workspace = true }
serde_json = { workspace = true }
